runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
  - name: flask
    version: 0.12
  - name: jinja2
    version: 2.6
  - name: werkzeug
    version: 0.11.10
  - name: ssl
    version: latest

env_variables:
  LOCAL_APP_CONFIG_PATH: 'dev/config.yaml'
  REMOTE_APP_CONFIG_PATH: 'configs/pins4days.yaml'
